tools/gcc/git(41):ERROR:105: Unable to locate a modulefile for 'tools/gcc/git/2.8.2'
              total        used        free      shared  buff/cache   available
Mem:         128674       14290       58833         752       55550      113029
Swap:         16383         465       15918
/opt/site/sge/default/spool/node649/job_scripts/2483583: line 14: nvidia-smi: command not found
2021-06-02 09:07:36.548986: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2021-06-02 09:07:55.373821: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-06-02 09:07:55.379138: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-06-02 09:07:55.379159: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-06-02 09:07:55.379187: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (node649.pri.csf3.alces.network): /proc/driver/nvidia/version does not exist
2021-06-02 09:07:55.383600: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-06-02 09:07:55.385062: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-06-02 09:08:02.031215: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-06-02 09:08:02.032213: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2600000000 Hz
WARNING:tensorflow:AutoGraph could not transform <function custom_mse at 0x2abb6bb54940> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
MODEL NAME = step1_without_trainable
Epoch 1/10
316/316 - 1852s - loss: 0.7100 - presence_loss: 0.4468 - coordinates_loss: 0.2632 - presence_accuracy: 0.7866
Epoch 2/10
316/316 - 1856s - loss: 0.1697 - presence_loss: 0.1447 - coordinates_loss: 0.0250 - presence_accuracy: 0.9523
Epoch 3/10
316/316 - 1870s - loss: 0.2351 - presence_loss: 0.1509 - coordinates_loss: 0.0842 - presence_accuracy: 0.9496
Epoch 4/10
316/316 - 1863s - loss: 0.1052 - presence_loss: 0.0983 - coordinates_loss: 0.0070 - presence_accuracy: 0.9671
Epoch 5/10
316/316 - 1851s - loss: nan - presence_loss: 0.0713 - coordinates_loss: nan - presence_accuracy: 0.9764
Epoch 6/10
316/316 - 1860s - loss: 0.0707 - presence_loss: 0.0666 - coordinates_loss: 0.0041 - presence_accuracy: 0.9800
Epoch 7/10
316/316 - 1877s - loss: 0.0645 - presence_loss: 0.0606 - coordinates_loss: 0.0039 - presence_accuracy: 0.9824
Epoch 8/10
316/316 - 1874s - loss: 0.0572 - presence_loss: 0.0531 - coordinates_loss: 0.0041 - presence_accuracy: 0.9830
