tools/gcc/git(41):ERROR:105: Unable to locate a modulefile for 'tools/gcc/git/2.8.2'
              total        used        free      shared  buff/cache   available
Mem:         128674        9202      113781         278        5690      118581
Swap:         16383         839       15544
/opt/site/sge/default/spool/node639/job_scripts/2481283: line 14: nvidia-smi: command not found
2021-05-31 17:20:58.674264: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2021-05-31 17:21:32.051068: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-05-31 17:21:32.057757: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-05-31 17:21:32.057788: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-05-31 17:21:32.057819: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (node639.pri.csf3.alces.network): /proc/driver/nvidia/version does not exist
2021-05-31 17:21:32.076041: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-05-31 17:21:32.077515: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-05-31 17:21:38.481285: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-05-31 17:21:38.482340: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2600265000 Hz
WARNING:tensorflow:AutoGraph could not transform <function custom_mse at 0x2aee13c849d0> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
MODEL NAME = optimized_for_non_pretrained
Epoch 1/10
WARNING:tensorflow:AutoGraph could not transform <function custom_crossentropy at 0x2aee04d141f0> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
313/313 - 1551s - loss: 2.2755 - presence_loss: 0.4630 - coordinates_loss: 0.0766 - letter_loss: 1.7359 - presence_accuracy: 0.7689
Epoch 2/10
313/313 - 1534s - loss: 1.6014 - presence_loss: 0.2294 - coordinates_loss: 0.0382 - letter_loss: 1.3338 - presence_accuracy: 0.9138
Epoch 3/10
313/313 - 1535s - loss: 1.3711 - presence_loss: 0.1360 - coordinates_loss: 0.0335 - letter_loss: 1.2017 - presence_accuracy: 0.9538
Epoch 4/10
313/313 - 1534s - loss: 1.2683 - presence_loss: 0.0948 - coordinates_loss: 0.0308 - letter_loss: 1.1427 - presence_accuracy: 0.9682
Epoch 5/10
313/313 - 1536s - loss: 1.1878 - presence_loss: 0.0824 - coordinates_loss: 0.0277 - letter_loss: 1.0777 - presence_accuracy: 0.9728
Epoch 6/10
313/313 - 1533s - loss: 1.1697 - presence_loss: 0.0637 - coordinates_loss: 0.0254 - letter_loss: 1.0806 - presence_accuracy: 0.9774
Epoch 7/10
313/313 - 1536s - loss: 1.1416 - presence_loss: 0.0590 - coordinates_loss: 0.0242 - letter_loss: 1.0583 - presence_accuracy: 0.9784
Epoch 8/10
313/313 - 1559s - loss: 1.1525 - presence_loss: 0.0691 - coordinates_loss: 0.0249 - letter_loss: 1.0584 - presence_accuracy: 0.9791
Epoch 9/10
313/313 - 1660s - loss: 1.1258 - presence_loss: 0.0531 - coordinates_loss: 0.0222 - letter_loss: 1.0504 - presence_accuracy: 0.9824
Epoch 10/10
313/313 - 1758s - loss: 1.1369 - presence_loss: 0.0505 - coordinates_loss: 0.0236 - letter_loss: 1.0628 - presence_accuracy: 0.9846
2021-05-31 21:44:02.075986: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
