tools/gcc/git(41):ERROR:105: Unable to locate a modulefile for 'tools/gcc/git/2.8.2'
              total        used        free      shared  buff/cache   available
Mem:         128677        2210      118072         715        8393      125139
Swap:         16383         492       15891
/opt/site/sge/default/spool/node740/job_scripts/2482445: line 14: nvidia-smi: command not found
2021-06-01 15:17:46.443256: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2021-06-01 15:17:55.267179: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-06-01 15:17:55.267770: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-06-01 15:17:55.267788: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-06-01 15:17:55.267818: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (node740.pri.csf3.alces.network): /proc/driver/nvidia/version does not exist
2021-06-01 15:17:55.268163: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-06-01 15:17:55.269191: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-06-01 15:18:00.207140: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-06-01 15:18:00.207615: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2399880000 Hz
WARNING:tensorflow:AutoGraph could not transform <function custom_mse at 0x2b2da3f6ca60> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
MODEL NAME = step1_224_noletter_nopretrain_2
Epoch 1/10
316/316 - 1163s - loss: 0.3703 - presence_loss: 0.2975 - coordinates_loss: 0.0728 - presence_accuracy: 0.8717
Epoch 2/10
316/316 - 1153s - loss: 0.1658 - presence_loss: 0.1431 - coordinates_loss: 0.0227 - presence_accuracy: 0.9512
Epoch 3/10
316/316 - 1141s - loss: 0.1082 - presence_loss: 0.0914 - coordinates_loss: 0.0168 - presence_accuracy: 0.9690
Epoch 4/10
316/316 - 1138s - loss: 0.0857 - presence_loss: 0.0720 - coordinates_loss: 0.0137 - presence_accuracy: 0.9765
Epoch 5/10
316/316 - 1160s - loss: 0.0832 - presence_loss: 0.0691 - coordinates_loss: 0.0142 - presence_accuracy: 0.9775
Epoch 6/10
316/316 - 1171s - loss: 0.0743 - presence_loss: 0.0630 - coordinates_loss: 0.0113 - presence_accuracy: 0.9796
Epoch 7/10
316/316 - 1172s - loss: 0.0668 - presence_loss: 0.0542 - coordinates_loss: 0.0126 - presence_accuracy: 0.9834
Epoch 8/10
316/316 - 1173s - loss: nan - presence_loss: 0.0555 - coordinates_loss: nan - presence_accuracy: 0.9811
Epoch 9/10
316/316 - 1176s - loss: 0.0529 - presence_loss: 0.0424 - coordinates_loss: 0.0105 - presence_accuracy: 0.9872
Epoch 10/10
316/316 - 1312s - loss: 0.0547 - presence_loss: 0.0450 - coordinates_loss: 0.0098 - presence_accuracy: 0.9868
2021-06-01 18:34:05.497324: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
