tools/gcc/git(41):ERROR:105: Unable to locate a modulefile for 'tools/gcc/git/2.8.2'
              total        used        free      shared  buff/cache   available
Mem:         128674        1622      125295          49        1756      126446
Swap:         16383           0       16383
/opt/site/sge/default/spool/node693/job_scripts/2483231: line 14: nvidia-smi: command not found
2021-06-01 21:27:03.195768: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2021-06-01 21:27:23.555631: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-06-01 21:27:23.560257: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-06-01 21:27:23.560300: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-06-01 21:27:23.560346: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (node693.pri.csf3.alces.network): /proc/driver/nvidia/version does not exist
2021-06-01 21:27:23.564749: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-06-01 21:27:23.566085: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-06-01 21:27:28.357280: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-06-01 21:27:28.357700: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2600190000 Hz
WARNING:tensorflow:AutoGraph could not transform <function custom_mse at 0x2ae64317ba60> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
MODEL NAME = step1_224_noletter_nopretrain_no_GAP_no_dropout
Epoch 1/10
316/316 - 1224s - loss: 0.8012 - presence_loss: 0.5119 - coordinates_loss: 0.2893 - presence_accuracy: 0.7429
Epoch 2/10
316/316 - 1229s - loss: nan - presence_loss: 0.1861 - coordinates_loss: nan - presence_accuracy: 0.9339
Epoch 3/10
316/316 - 1333s - loss: 0.1418 - presence_loss: 0.1321 - coordinates_loss: 0.0097 - presence_accuracy: 0.9590
Epoch 4/10
316/316 - 1417s - loss: 0.1277 - presence_loss: 0.1137 - coordinates_loss: 0.0140 - presence_accuracy: 0.9616
Epoch 5/10
316/316 - 1426s - loss: 0.0936 - presence_loss: 0.0826 - coordinates_loss: 0.0110 - presence_accuracy: 0.9729
Epoch 6/10
316/316 - 1420s - loss: 0.0739 - presence_loss: 0.0673 - coordinates_loss: 0.0066 - presence_accuracy: 0.9786
Epoch 7/10
316/316 - 1412s - loss: 0.0584 - presence_loss: 0.0536 - coordinates_loss: 0.0048 - presence_accuracy: 0.9833
Epoch 8/10
316/316 - 1223s - loss: 0.0591 - presence_loss: 0.0550 - coordinates_loss: 0.0041 - presence_accuracy: 0.9835
Epoch 9/10
316/316 - 1223s - loss: 0.0561 - presence_loss: 0.0524 - coordinates_loss: 0.0037 - presence_accuracy: 0.9850
Epoch 10/10
316/316 - 1226s - loss: 0.0524 - presence_loss: 0.0485 - coordinates_loss: 0.0039 - presence_accuracy: 0.9843
2021-06-02 01:06:25.557178: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
